---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  annotations:
    flux.weave.works/automated: 'true'
spec:
  minReadySeconds: 5
  replicas: 3
  template:
    metadata:
      labels:
        name: helloworld
    spec:
      containers:
      - name: helloworld
        image: sebidude/helloworld:1.0.4
        args:
        - -msg=Ahoy
        ports:
        - containerPort: 80
      - name: sidecar
        image: quay.io/weaveworks/sidecar:master-a000002
        args:
        - -addr=:8080
        ports:
        - containerPort: 8080
